### ISSUE TITLE
subprocess.CalledProcessError and UnicodeDecodeError

### ISSUE THREAD

**Issue by DrWiki** [facebookresearch/3D-Vision-and-Touch#1]
D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py:190: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py", line 961, in _build_extension_module
    check=True)
  File "D:\Anaconda\envs\Tensorflow115\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/TBSI-RD/code/3D-Vision-and-Touch/touch_charts/recon.py", line 19, in <module>
    import utils
  File "..\utils.py", line 17, in <module>
    from third_party_code import ChamferDistance
  File "..\third_party_code\__init__.py", line 6, in <module>
    from .chamfer_distance import ChamferDistance
  File "..\third_party_code\chamfer_distance.py", line 10, in <module>
    "../third_party_code/chamfer_distance.cu"])
  File "D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py", line 659, in load
    is_python_module)
  File "D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py", line 828, in _jit_compile
    with_cuda=with_cuda)
  File "D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py", line 881, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "D:\Anaconda\envs\Tensorflow115\lib\site-packages\torch\utils\cpp_extension.py", line 973, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1183: invalid continuation byte

This is the error log， I just cloned the project and run recon.py in the environment of python3.7 and pytorch1.6.0.
Could you please help me remove this error?

**Comment by EdwardSmith1884** [comment]
I should be releasing a new version which will fix this this week some time.

**Comment by EdwardSmith1884** [comment]
I just uploaded a major overhaul of the code. Can you try again and see if it works now?
